name: Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18.5'

      - name: Build app
        run: GOOS=linux go build -o main

      - name: Bump version
        uses: anothrNick/github-tag-action@1.36.0
        id: bump
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DRY_RUN: true
          RELEASE_BRANCHES: main
          DEFAULT_BUMP: patch

      - name: Docker build and push 
        run: |
          docker login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io
          docker build -t codeforkansascity/reusefull-web-app:${{ steps.bump.outputs.new_tag }} . 
          docker push ghcr.io/codeforkansascity/reusefull-web-app:${{ steps.bump.outputs.new_tag }}

      - name: Push tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          RELEASE_BRANCHES: main
          DEFAULT_BUMP: patch
