name: Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18.5'

      - name: Build app
        run: GOOS=linux go build -o main

      - name: Bump version
        uses: anothrNick/github-tag-action@1.26.0
        id: bump
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DRY_RUN: true
          RELEASE_BRANCHES: main
          DEFAULT_BUMP: patch

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: codeforkansascity/reusefull-web-app:${{ steps.bump.outputs.new_tag }}

      - name: Push tag
        uses: anothrNick/github-tag-action@1.26.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          RELEASE_BRANCHES: main
          DEFAULT_BUMP: patch


      # - name: Slack Notification
      #   uses: rtCamp/action-slack-notify@master
      #   env:
      #     SLACK_USERNAME: reusefull
      #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      #     SLACK_TITLE: Build
      #     SLACK_MESSAGE: Created reusefull:${{ steps.bump.outputs.new_tag }}
      #     SLACK_ICON_EMOJI: ':hyprcubd:'
      #     SLACK_FOOTER:
